### ISSUE TITLE
cant print the gantt chart

### ISSUE THREAD

**Issue by machine1104** [MrdotCai/tabuSearchForJSP#1]
how can i use the json to plot the gantt chart?
thanks

**Comment by MrdotCai** [comment]
The json is for this:
https://github.com/stefanSchinkel/gantt/tree/master
But you need to change some python files a little bit.
[gantt-github.zip](https://github.com/MrdotCai/tabuSearchForJSP/files/6727360/gantt-github.zip)

**Comment by machine1104** [comment]
perfect
worked like a charm
